---
- name: Configure ArgoCD for Ingress
  hosts: kops
  become: true
  tasks:
    - name: Patch ArgoCD server to run in insecure mode
      ansible.builtin.command: |
        kubectl patch deployment argocd-server -n argocd --type='json' \
        -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--insecure"}]'
        
    - name: Wait for ArgoCD server to restart
      ansible.builtin.command: "kubectl rollout status deployment/argocd-server -n argocd"
      
    - name: Copy updated ArgoCD Ingress template
      ansible.builtin.template:
        src: ../templates/argoingress.yaml
        dest: /tmp/argoingress.yaml
        
    - name: Apply updated ingress
      ansible.builtin.command: "kubectl apply -f /tmp/argoingress.yaml"
